version: 0.0
os: linux
files:
  - source: kafka_2.12-1.1.0.tgz
    destination: /kafka
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
    - location: scripts/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
