version: 0.0
os: linux
files:
  - source: /kafka/1.1.0/kafka_2.12-1.1.0.tgz
    destination: /app/inst/1.1.0/kafka_2.12-1.1.0.tgz
hooks:
  BeforeInstall:
    - location: kafka/1.1.0/scripts/install_dependencies.sh
      timeout: 600
    - location: kafka/1.1.0/scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: kafka/1.1.0/scripts/stop_server.sh
      timeout: 300
